# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
