# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0002_donate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_contact', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='donate',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationmatch',
            name='donate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Donate'),
        ),
        migrations.AddField(
            model_name='donationmatch',
            name='interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
