# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_requestmatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmatch',
            old_name='donate',
            new_name='request',
        ),
    ]
