# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20161023_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donate',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactMethod'),
        ),
    ]
