# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20161111_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Acceptable', 'Acceptable')], default='New', max_length=15),
        ),
        migrations.AddField(
            model_name='donate',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
