# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_auto_20161118_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.Category'),
        ),
        migrations.AddField(
            model_name='donate',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.SubCategory'),
        ),
    ]
