# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contactMethod',
            new_name='contact_method',
        ),
    ]
